#!/usr/bin/env node
// Scan a Next.js project for supabase-js usage and write MIGRATION.md (a checklist for the rewrite).
// Usage: node inventory.mjs <dir> [--import-json <dbm import --json output>] [--out MIGRATION.md]
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, relative } from 'node:path';

const args = process.argv.slice(2);
const dir = args[0] && !args[0].startsWith('--') ? args[0] : process.cwd();
const opt = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const out = opt('--out') ?? 'MIGRATION.md';
const outFile = isAbsolute(out) ? out : join(dir, out);
const importJson = opt('--import-json');
const report = importJson ? JSON.parse(readFileSync(importJson, 'utf8')) : null;

const SKIP = new Set(['node_modules', '.next', 'dist', '.git', 'out', 'coverage']);
const EXT = /\.(tsx?|jsx?|mjs|cjs)$/;
const KINDS = [
  {
    kind: 'client-init',
    short:
      'delete the client; import `db` from `@/lib/db` in server code, `authClient` from `@/lib/auth-client` in client code',
    re: /\b(createClient|createBrowserClient|createServerClient)\s*\(/,
    target:
      'delete; server code imports `db` from `@/lib/db`, client code imports `authClient` from `@/lib/auth-client`',
  },
  {
    kind: 'storage',
    short:
      'presigned URLs from `@/lib/s3`; public files via `S3_PUBLIC_BASE_URL` after `dbm storage public <slug>`',
    re: /\.storage\s*\./,
    target:
      'presigned URLs from `@/lib/s3` (`getPresignedUploadUrl` / `getPresignedDownloadUrl`); public files via `S3_PUBLIC_BASE_URL` after `dbm storage public <slug>`',
  },
  {
    kind: 'query',
    short: 'Drizzle query in a server action or route handler; client components call the action',
    re: /(?<!\.storage)\.from\s*\(/,
    target:
      'Drizzle query inside a server action or route handler; client components call the action',
  },
  {
    kind: 'auth',
    short:
      'better-auth: authClient.signIn/signUp/signOut/useSession on the client; auth.api.getSession({ headers: await headers() }) on the server',
    re: /\.auth\s*\./,
    target:
      'better-auth: `authClient.signIn.email` / `signUp.email` / `signOut` / `useSession` (client); `auth.api.getSession({ headers: await headers() })` (server)',
  },
  {
    kind: 'realtime',
    short:
      'not provided by dbm: use polling, server-sent events, or a later LISTEN/NOTIFY bridge (decide manually)',
    re: /\.channel\s*\(|postgres_changes/,
    target:
      'not provided by dbm: polling, server-sent events, or a later LISTEN/NOTIFY bridge (decide manually)',
  },
  {
    kind: 'rpc',
    short:
      'call the SQL function via Drizzle sql tagged template from a server action, or move the logic to TypeScript',
    re: /\.rpc\s*\(/,
    target:
      'call the SQL function with Drizzle ``sql`select fn(...)` `` from a server action, or move the logic to TypeScript',
  },
  {
    kind: 'edge-function',
    short: 'Next.js route handler or server action (manual)',
    re: /\.functions\s*\.invoke\s*\(/,
    target: 'Next.js route handler or server action (manual)',
  },
];

function walk(d, acc = []) {
  for (const name of readdirSync(d)) {
    if (SKIP.has(name)) continue;
    const p = join(d, name);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (EXT.test(name)) acc.push(p);
  }
  return acc;
}

const SECRET =
  /eyJ[A-Za-z0-9_-]{10,}(?:\.[A-Za-z0-9_-]+){0,2}|sb_(?:secret|publishable)_[A-Za-z0-9_-]+/g;
const redact = (t) => t.replace(SECRET, '[redacted]');

const usages = [];
const files = new Set();
for (const file of walk(dir)) {
  const text = readFileSync(file, 'utf8');
  if (!/@supabase\//.test(text) && !/\bsupabase\b/.test(text)) continue;
  const rel = relative(dir, file);
  const isClient = /^(?:\uFEFF|\s|\/\/[^\n]*\n|\/\*[\s\S]*?\*\/)*["']use client["']/.test(text);
  text.split('\n').forEach((line, i) => {
    for (const k of KINDS) {
      if (!k.re.test(line)) continue;
      usages.push({
        file: rel,
        line: i + 1,
        kind: k.kind,
        snippet: redact(line.trim()).slice(0, 100),
        isClient,
      });
      files.add(rel);
    }
  });
}

const byKind = Object.fromEntries(
  KINDS.map((k) => [k.kind, usages.filter((u) => u.kind === k.kind).length]),
);
const policies = report?.rlsPolicies ?? [];
const importErrors = report ? Object.values(report.errors ?? {}).flat() : [];
const clientQueries = usages.filter((u) => u.isClient && (u.kind === 'query' || u.kind === 'rpc'));

const md = [];
md.push('# Migration checklist: Supabase -> dbm', '');
md.push(
  `Generated by /dbmanager. ${usages.length} supabase-js usages in ${files.size} files. Rewrite each item, delete it from this list, and run \`/dbmanager cutover\` when the list is empty.`,
  '',
);
md.push('## 1. Mapping', '', '| kind | count | target pattern |', '|---|---|---|');
for (const k of KINDS) md.push(`| \`${k.kind}\` | ${byKind[k.kind]} | ${k.target} |`);
md.push('');
if (clientQueries.length) {
  md.push(
    '## 2. Client components that touch the database ("use client" + query/rpc)',
    '',
    'These move to server actions; the component keeps only the call.',
    '',
  );
  for (const u of clientQueries) md.push(`- [ ] ${u.file}:${u.line} \`${u.snippet}\``);
  md.push('');
}
md.push('## 3. Per file', '');
for (const f of [...files].sort()) {
  md.push(`### ${f}`, '');
  for (const u of usages.filter((x) => x.file === f)) {
    const first = KINDS.find((k) => k.kind === u.kind).short;
    md.push(`- [ ] L${u.line} \`${u.kind}\` -> ${first}  \n  \`${u.snippet}\``);
  }
  md.push('');
}
md.push('## 4. Schema items from `dbm import`', '');
if (!report) {
  md.push(
    '_Run `dbm import <slug> --from <url> --json > .dbm-import.json` and re-run the inventory with `--import-json .dbm-import.json` to fill this section._',
    '',
  );
} else {
  md.push(`### RLS policies to re-implement in server code (${policies.length})`, '');
  for (const p of policies) md.push(`- [ ] ${p}`);
  md.push('', `### Import errors to fix in the schema (${importErrors.length})`, '');
  for (const e of importErrors) md.push(`- [ ] ${e}`);
  if (report.mismatched?.length)
    md.push('', `**Count mismatches:** ${report.mismatched.join(', ')}`);
  if (report.usersExported != null) {
    md.push(
      '',
      `Users exported: ${report.usersExported} (see the Users section of docs/migration-from-supabase.md)`,
    );
  }
  md.push('');
}
md.push(
  '## 5. Always',
  '',
  '- [ ] Foreign keys to `auth.users(id)` -> `"user"(id)`',
  '- [ ] Remove `NEXT_PUBLIC_SUPABASE_*` / `SUPABASE_*` env vars after cutover',
  '- [ ] `npm rm @supabase/supabase-js @supabase/ssr` after the last usage is gone',
  '- [ ] OAuth identities (`auth.identities`) are not migrated automatically',
  '',
);
writeFileSync(outFile, md.join('\n'));
console.log(
  `MIGRATION.md: ${usages.length} usages in ${files.size} files, ${policies.length} policies, ${importErrors.length} import errors`,
);
