export interface GarageTomlOptions {
  webDomain: string;
}

/** Secrets come from env (GARAGE_RPC_SECRET, GARAGE_ADMIN_TOKEN); the file has none. */
export function renderGarageToml(o: GarageTomlOptions): string {
  return `# Garage v2.4.x single-node configuration, generated by dbm.
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/snapshots"

replication_factor = 1
consistency_mode = "consistent"

db_engine = "lmdb"
metadata_fsync = true
data_fsync = false
metadata_auto_snapshot_interval = "6h"

block_size = "1M"
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".${o.webDomain}"
index = "index.html"
add_host_to_metrics = false

[admin]
api_bind_addr = "[::]:3903"
metrics_require_token = true
`;
}
